# Generated by Django 6.0.7 on 2026-08-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('usage_batiment', models.CharField(choices=[('habitation', 'Habitation'), ('commerce', 'Commerce'), ('bureau', 'Bureau'), ('industriel', 'Industriel')], max_length=50)),
                ('nb_niveaux', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementStructurel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('poteau', 'Poteau'), ('poutre', 'Poutre'), ('semelle', 'Semelle')], max_length=20)),
                ('identifiant', models.CharField(help_text="Ex. 'P1', 'PT-RDC-2' -- repère de l'élément dans le plan", max_length=50)),
                ('portee', models.FloatField(blank=True, help_text='mètres, pour une poutre', null=True)),
                ('charge_lineaire', models.FloatField(blank=True, help_text='kN/m, pour une poutre', null=True)),
                ('charge_calculee', models.FloatField(blank=True, help_text="kN, charge reprise par l'élément (poteau/semelle)", null=True)),
                ('hauteur_poteau', models.FloatField(blank=True, help_text='mètres', null=True)),
                ('taux_travail_sol', models.FloatField(blank=True, help_text='bars, pour une semelle', null=True)),
                ('resultat_calcul', models.JSONField(blank=True, help_text='Dict retourné par le moteur de calcul', null=True)),
                ('resultat_valide', models.JSONField(blank=True, help_text='Valeurs finales après validation/ajustement humain', null=True)),
                ('statut', models.CharField(choices=[('propose', 'Proposé'), ('modifie', 'Modifié'), ('valide', 'Validé')], default='propose', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projets.projet')),
            ],
        ),
    ]
