# Generated by Django 6.0.7 on 2026-08-03 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteMainDoeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Ex. 'Main d'œuvre coffrage', 'Terrassement/fouilles'", max_length=255)),
                ('unite', models.CharField(help_text="Ex. 'm²', 'kg', 'forfait', 'm³'", max_length=20)),
                ('quantite', models.FloatField()),
                ('prix_unitaire', models.FloatField(help_text='FCFA')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_main_doeuvre', to='projets.projet')),
            ],
        ),
    ]
