# Generated by Django 6.0.7 on 2026-08-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_postemaindoeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='poteau_associe',
            field=models.ForeignKey(blank=True, help_text="Poteau supporté par cette semelle (uniquement si type_element == 'semelle')", limit_choices_to={'type_element': 'poteau'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semelles_associees', to='projets.elementstructurel'),
        ),
        migrations.CreateModel(
            name='CoucheCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Ex: Carrelage + mortier de pose', max_length=150)),
                ('epaisseur_cm', models.FloatField(help_text='Épaisseur en cm')),
                ('poids_volumique_kn_m3', models.FloatField(help_text='Poids volumique en kN/m³')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couches_charges', to='projets.elementstructurel')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couches_charges', to='projets.projet')),
            ],
        ),
    ]
