# Generated by Django 6.0.7 on 2026-08-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_postemaindoeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='position',
            field=models.CharField(blank=True, choices=[('infrastructure', 'Infrastructure'), ('superstructure', 'Superstructure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='position_x',
            field=models.FloatField(blank=True, help_text='mètres, origine (0,0) = coin de la trame', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='position_y',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='poteau_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semelles_associees', to='projets.elementstructurel'),
        ),
        migrations.AddField(
            model_name='projet',
            name='charge_exploitation',
            field=models.FloatField(blank=True, help_text='kN/m² -- si vide, déduit de usage_batiment', null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='hauteur_etage',
            field=models.FloatField(default=3.0, help_text="Hauteur d'étage en mètres"),
        ),
        migrations.AddField(
            model_name='projet',
            name='nb_travees_x',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projet',
            name='nb_travees_y',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projet',
            name='plan_fondation_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='portee_x',
            field=models.FloatField(default=4.0, help_text='Portée en mètres, direction X'),
        ),
        migrations.AddField(
            model_name='projet',
            name='portee_y',
            field=models.FloatField(default=4.0, help_text='Portée en mètres, direction Y'),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='charge_calculee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='charge_lineaire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='hauteur_poteau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='identifiant',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='resultat_calcul',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='resultat_valide',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='statut',
            field=models.CharField(choices=[('propose', 'Proposé'), ('modifie', 'Modifié'), ('valide', 'Validé')], default='propose', max_length=10),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='taux_travail_sol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='type_element',
            field=models.CharField(choices=[('poteau', 'Poteau'), ('poutre', 'Poutre'), ('semelle', 'Semelle Isolée'), ('dalle', 'Dalle Pleine'), ('semelle_filante', 'Semelle Filante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nb_niveaux',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projet',
            name='usage_batiment',
            field=models.CharField(default='habitation', max_length=100),
        ),
        migrations.CreateModel(
            name='CoucheCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('epaisseur_cm', models.FloatField(help_text='Épaisseur en cm')),
                ('poids_volumique_kn_m3', models.FloatField(help_text='Poids volumique en kN/m³')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couches_charges', to='projets.elementstructurel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couches_charges', to='projets.projet')),
            ],
        ),
        migrations.CreateModel(
            name='PosteComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(choices=[('lot_00_generalites', 'Généralités'), ('lot_01_terrassement', 'Terrassement'), ('lot_02_gros_oeuvre_infrastructure', 'Gros Œuvre - Infrastructure'), ('lot_02_gros_oeuvre_superstructure', 'Gros Œuvre - Superstructure'), ('lot_03_etancheite', 'Étanchéité'), ('lot_04_plomberie', 'Plomberie'), ('lot_05_assainissement', 'Assainissement'), ('lot_06_electricite', 'Électricité'), ('lot_07_charpente', 'Charpente'), ('lot_08_couverture', 'Couverture')], max_length=50)),
                ('mode', models.CharField(choices=[('simple', 'Poste simple'), ('ratio', 'Poste à ratio')], default='simple', max_length=10)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('prix_unitaire', models.FloatField(blank=True, null=True)),
                ('type_poste', models.CharField(blank=True, choices=[('maconnerie_pleine', 'Maçonnerie agglos pleins'), ('maconnerie_creuse', 'Maçonnerie agglos creux'), ('enduit', 'Enduit'), ('chainage', 'Chaînage'), ('raidisseur', 'Raidisseur'), ('acrotere', 'Acrotère')], max_length=30)),
                ('geometrie', models.JSONField(blank=True, null=True)),
                ('lignes_calculees', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_complementaires', to='projets.projet')),
            ],
        ),
        migrations.DeleteModel(
            name='PosteMainDoeuvre',
        ),
    ]
