# Generated by Django 6.0.7 on 2026-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_elementstructurel_poteau_associe_couchecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementstructurel',
            name='type_element',
            field=models.CharField(choices=[('poteau', 'Poteau'), ('poutre', 'Poutre'), ('semelle', 'Semelle'), ('dalle', 'Dalle Pleine'), ('semelle_filante', 'Semelle Filante')], max_length=20),
        ),
    ]
