# Generated by Django 6.0.7 on 2026-08-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_alter_elementstructurel_type_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='longueur_m',
            field=models.FloatField(blank=True, help_text='mètres, pour une semelle filante -- longueur totale du mur porté', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='surface_m2',
            field=models.FloatField(blank=True, help_text='m², pour une dalle -- surface totale à couler', null=True),
        ),
    ]