# Generated by Django 6.0.7 on 2026-08-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_remove_elementstructurel_longueur_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='longueur_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Longueur (m)'),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='surface_m2',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface (m²)'),
        ),
    ]
