# Generated by Django 6.0.7 on 2026-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_elementstructurel_longueur_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseParametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('siege_social', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.CharField(blank=True, max_length=200)),
                ('rccm', models.CharField(blank=True, max_length=100, verbose_name='N° R.C.C.M')),
                ('cc', models.CharField(blank=True, max_length=100, verbose_name='CC N°')),
                ('cb', models.CharField(blank=True, max_length=100, verbose_name='CB N°')),
                ('capital_social', models.CharField(blank=True, max_length=100)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='numero_devis',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]