# Generated by Django 6.1 on 2026-08-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_entrepriseparametres_projet_numero_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementstructurel',
            name='type_element',
            field=models.CharField(choices=[('poteau', 'Poteau'), ('poutre', 'Poutre'), ('semelle', 'Semelle Isolée'), ('dalle', 'Dalle Pleine'), ('semelle_filante', 'Semelle Filante'), ('longrine', 'Longrine'), ('chainage', 'Chaînage')], max_length=20),
        ),
    ]