# Generated by Django 6.0.7 on 2026-08-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0009_alter_elementstructurel_type_element '),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='fichier_import_origine',
            field=models.FileField(blank=True, null=True, upload_to='imports_ifc/'),
        ),
    ]