# Generated by Django 6.0.7 on 2026-08-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0010_projet_fichier_import_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='poteau_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages_destination', to='projets.elementstructurel'),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='poteau_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages_origine', to='projets.elementstructurel'),
        ),
    ]
