# Generated by Django 6.0.7 on 2026-08-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0011_elementstructurel_poteau_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstructurel',
            name='avec_degression',
            field=models.BooleanField(default=True, help_text="Applique la loi de dégression NF P06-001 sur les charges d'exploitation cumulées"),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='epaisseur_dalle',
            field=models.FloatField(blank=True, help_text='mètres -- ignoré si des CoucheCharge sont liées à cet élément (Module 2)', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='nb_niveaux_charges',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de niveaux (toiture comprise) dont la charge descend sur ce poteau', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='portee_arriere',
            field=models.FloatField(blank=True, help_text="mètres -- portée de la travée à l'arrière de ce poteau", null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='portee_avant',
            field=models.FloatField(blank=True, help_text="mètres -- portée de la travée à l'avant de ce poteau", null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='portee_droite',
            field=models.FloatField(blank=True, help_text='mètres -- portée de la travée à droite de ce poteau', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='portee_gauche',
            field=models.FloatField(blank=True, help_text='mètres -- portée de la travée à gauche de ce poteau', null=True),
        ),
        migrations.AddField(
            model_name='elementstructurel',
            name='usage_toiture',
            field=models.CharField(blank=True, help_text="Usage du niveau le plus haut si différent des étages courants (ex. 'toiture_terrasse') -- vide = même usage que le projet", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='couchecharge',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couches_charges', to='projets.projet'),
        ),
    ]
