# Generated by Django 6.0.7 on 2026-09-19 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_elementstructurel_avec_degression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAppelIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('MOCK', 'Mock Client'), ('GEMINI', 'Gemini AI'), ('FALLBACK_LOCAL', 'Fallback Local')], max_length=30)),
                ('duree_ms', models.IntegerField(blank=True, null=True)),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'appel IA",
                'verbose_name_plural': "Journaux d'appels IA",
                'ordering': ['-date_appel'],
            },
        ),
    ]
