# Generated by Django 6.0.7 on 2026-09-20 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0012_elementstructurel_avec_degression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_cabinet', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='avec_degression',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='epaisseur_dalle',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='nb_niveaux_charges',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_arriere',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_avant',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_droite',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_gauche',
            field=models.FloatField(blank=True, help_text='mètres', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='usage_toiture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='projets.entreprise'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur Cabinet'), ('INGENIEUR', "Ingénieur d'Études"), ('TECHNICIEN', 'Technicien / Dessinateur')], default='INGENIEUR', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='projets.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
