# Generated by Django 6.0.7 on 2026-09-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_entreprise_projet_cree_par_and_more'),
        ('projets', '0013_journalappelia'),
    ]

    operations = [
    ]
