# Generated by Django 6.0.7 on 2026-09-19 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0013_journalappelia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projet',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text='Cabinet (entreprise) propriétaire de ce projet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='projets.entrepriseparametres'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('technicien', 'Technicien'), ('ingenieur', 'Ingénieur'), ('admin', 'Admin (Gérant du cabinet)')], default='technicien', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', to='projets.entrepriseparametres')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
