# Generated by Django 6.0.7 on 2026-10-01 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0014_merge_20260923_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='telephone',
        ),
        migrations.AddField(
            model_name='entrepriseparametres',
            name='prix_unitaires',
            field=models.JSONField(blank=True, default=dict, help_text='Prix unitaires propres à ce cabinet (FCFA), ex. {"beton_m3": 95000, "ciment_t": 110000}. Les clés absentes retombent sur le barème par défaut du moteur de calcul.'),
        ),
        migrations.AddField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='avec_degression',
            field=models.BooleanField(default=True, help_text="Applique la loi de dégression NF P06-001 sur les charges d'exploitation cumulées"),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='epaisseur_dalle',
            field=models.FloatField(blank=True, help_text='mètres -- ignoré si des CoucheCharge sont liées à cet élément (Module 2)', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='nb_niveaux_charges',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de niveaux (toiture comprise) dont la charge descend sur ce poteau', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_arriere',
            field=models.FloatField(blank=True, help_text="mètres -- portée de la travée à l'arrière de ce poteau", null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_avant',
            field=models.FloatField(blank=True, help_text="mètres -- portée de la travée à l'avant de ce poteau", null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_droite',
            field=models.FloatField(blank=True, help_text='mètres -- portée de la travée à droite de ce poteau', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='portee_gauche',
            field=models.FloatField(blank=True, help_text='mètres -- portée de la travée à gauche de ce poteau', null=True),
        ),
        migrations.AlterField(
            model_name='elementstructurel',
            name='usage_toiture',
            field=models.CharField(blank=True, help_text="Usage du niveau le plus haut si différent des étages courants (ex. 'toiture_terrasse') -- vide = même usage que le projet", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='entreprise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profils', to='projets.entrepriseparametres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('technicien', 'Technicien'), ('ingenieur', 'Ingénieur'), ('admin', 'Admin (Gérant du cabinet)')], default='technicien', max_length=20),
        ),
        migrations.AlterField(
            model_name='projet',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text='Cabinet (entreprise) propriétaire de ce projet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='projets.entrepriseparametres'),
        ),
    ]
