# Generated by Django 6.0.7 on 2026-10-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projets",
            "0015_alter_profil_options_rename_user_profil_utilisateur_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="contrainte_sol_kn_m2",
            field=models.FloatField(
                blank=True,
                help_text="kN/m² (1 bar = 100 kN/m²) -- vide = hypothèse par défaut signalée",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="elementstructurel",
            name="taux_travail_sol",
            field=models.FloatField(blank=True, help_text="kN/m²", null=True),
        ),
        migrations.AlterField(
            model_name="entrepriseparametres",
            name="prix_unitaires",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Barème de prix unitaires du cabinet (FCFA), ex. {"beton_m3": 95000, "acier_kg": 800}. Toute clé nécessaire au DQE et absente ici bloque la génération avec un message explicite.',
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="charge_exploitation",
            field=models.FloatField(
                blank=True,
                help_text="kN/m² -- si vide, déduit de usage_batiment (constantes.CHARGES_EXPLOITATION)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="hauteur_etage",
            field=models.FloatField(
                blank=True, help_text="Hauteur d'étage en mètres", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="nb_niveaux",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projet",
            name="nb_travees_x",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projet",
            name="nb_travees_y",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projet",
            name="portee_x",
            field=models.FloatField(
                blank=True, help_text="Portée en mètres, direction X", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="portee_y",
            field=models.FloatField(
                blank=True, help_text="Portée en mètres, direction Y", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="usage_batiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("habitation", "Habitation"),
                    ("commerce", "Commerce"),
                    ("bureau", "Bureau"),
                    ("industriel", "Industriel"),
                    ("balcon", "Balcon"),
                    ("circulation", "Circulation"),
                    ("toiture_terrasse", "Toiture terrasse"),
                    ("toiture_inaccessible", "Toiture inaccessible"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="EvenementProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("inscription", "Inscription d'un cabinet"),
                            ("connexion", "Connexion"),
                            ("projet_cree", "Projet créé"),
                            ("import_ifc", "Import IFC confirmé"),
                            ("trame_generee", "Trame générée"),
                            ("element_valide", "Élément validé"),
                            ("element_deverrouille", "Élément déverrouillé"),
                            ("dqe_genere", "DQE généré"),
                            ("dqe_exporte", "DQE exporté"),
                            ("appel_ia", "Appel assistant IA"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("donnees", models.JSONField(blank=True, default=dict)),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="projets.entrepriseparametres",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="projets.projet",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_produit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement produit",
                "verbose_name_plural": "Événements produit",
                "ordering": ["-date"],
            },
        ),
    ]
