# Generated by Django 6.0.7 on 2026-10-06 15:43

from django.db import migrations, models


def normaliser_types(apps, schema_editor):
    """maconnerie_pleine / maconnerie_creuse -> maconnerie (clé du moteur).
    Ces postes n'étaient de toute façon jamais calculables (type inconnu du
    moteur) : on les rend calculables sans perdre leur géométrie. Aucune
    ligne supprimée."""
    Poste = apps.get_model("projets", "PosteComplementaire")
    Poste.objects.filter(type_poste__in=["maconnerie_pleine", "maconnerie_creuse"]).update(type_poste="maconnerie")


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0017_normaliser_usage_batiment"),
    ]

    operations = [
        migrations.RunPython(normaliser_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="postecomplementaire",
            name="type_poste",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "maconnerie",
                        "Maçonnerie (agglos pleins en soubassement + creux en élévation)",
                    ),
                    ("enduit", "Enduit"),
                    ("chainage", "Chaînage"),
                    ("raidisseur", "Raidisseur"),
                    ("acrotere", "Acrotère"),
                ],
                max_length=30,
            ),
        ),
    ]
