# Generated by Django 6.0.7 on 2026-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0018_type_poste_canonique"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementstructurel",
            name="charge_service",
            field=models.FloatField(blank=True, help_text="kN, ELS G + Q", null=True),
        ),
        migrations.AddField(
            model_name="projet",
            name="charge_permanente_kn_m2",
            field=models.FloatField(
                blank=True,
                help_text="G des planchers en kN/m² (hors poids propre poutres/poteaux si ajouté séparément)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="couches_permanentes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Composition du plancher : [{designation, type | poids_surfacique_kn_m2 | epaisseur_m + poids_volumique_kn_m3}]",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="inclure_poids_propre_ossature",
            field=models.BooleanField(
                default=False,
                help_text="Ajouter le poids propre des poutres, poteaux et semelles à G (False = G l'inclut déjà)",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="methode_semelles",
            field=models.CharField(
                choices=[
                    ("ELU", "ELU : A² ≥ Nu / σsol (prudent)"),
                    ("ELS", "ELS : A² ≥ Ns / σsol (usage courant)"),
                ],
                default="ELU",
                help_text="Choix métier explicite ; ELU = comportement historique du moteur",
                max_length=3,
            ),
        ),
    ]
