# Generated by Django 6.0.7 on 2026-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0019_hypotheses_calcul_explicites"),
    ]

    operations = [
        migrations.AddField(
            model_name="elementstructurel",
            name="nombre_identiques",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="entrepriseparametres",
            name="nature_prix",
            field=models.CharField(
                choices=[
                    ("vente_ht", "Prix de vente HT (fourni-posé)"),
                    ("debourse_sec", "Déboursé sec (coût de revient)"),
                ],
                default="vente_ht",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entrepriseparametres",
            name="prix_unitaires_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="entrepriseparametres",
            name="taux_marge_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% appliqué au déboursé sec (frais généraux + bénéfice) -- seulement si nature = déboursé sec",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entrepriseparametres",
            name="taux_tva_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="% de TVA du cabinet -- vide = TTC non calculé (jamais de taux supposé)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
