# Generated by Django 6.0.7 on 2026-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0020_dqe_tracabilite_prix_niveaux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="inclure_poids_propre_ossature",
            field=models.BooleanField(
                default=True,
                help_text="Ajouter le poids propre des poutres, poteaux et semelles à G (False = G l'inclut déjà)",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="methode_semelles",
            field=models.CharField(
                choices=[
                    ("ELU", "ELU : A² ≥ Nu / σsol (prudent)"),
                    ("ELS", "ELS : A² ≥ Ns / σsol (usage courant)"),
                ],
                default="ELU",
                help_text="Choix métier explicite ; ELU = méthode validée par le technicien BTP (07/10/2026)",
                max_length=3,
            ),
        ),
    ]
